apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: threatstack-agent
spec:
  selector:
    matchLabels:
      name: "threatstack-agent"
  template:
    metadata:
      labels:
        name: "threatstack-agent"
      name: threatstack-agent
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image: threatstack/ts-docker2:latest
        imagePullPolicy: Always
        name: threatstack-agent
        env:
          - name: THREATSTACK_SETUP_ARGS
            value:  "-deploy-key <REPLACE_WITH_VALID_DEPLOY_KEY> -ruleset 'Base Rule Set, Docker Rule Set, Kubernetes Rule Set'"
          - name: THREATSTACK_CONFIG_ARGS
            value: "enable_kubes 1 enable_containers 1"
        securityContext:
          privileged: false
          capabilities:
            add: ["AUDIT_CONTROL", "AUDIT_READ", "CHOWN","DAC_OVERRIDE", "DAC_READ_SEARCH", "FOWNER", "FSETID", "SETGID", "SETUID", "SYS_ADMIN", "SYS_PTRACE"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: hostfs
            mountPath: /threatstackfs
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /
          name: hostfs
